### ISSUE TITLE
need new eflags for 64-bit single-float or soft-float ABI

### ISSUE THREAD

**Issue by xry111** [loongson/LoongArch-Documentation#13]
单精度浮点/软件浮点和正常的 LP64 代码是 ABI 不兼容的 (无法用 fa0-fa7 传参)，当前在 GCC 里面加了个特判，但是这并不是正确的做法：https://github.com/loongson/gcc/pull/31#issuecomment-930505737

**Comment by ChenghuaXu** [comment]
这个可以关了吧。相关改动已在其他pr中改了。

**Comment by xen0n** [comment]
+1 可关
