### ISSUE TITLE
中文版文档呢？放出来的怎么都是英文版文档呢？

### ISSUE THREAD

**Issue by cnmade** [loongson/LoongArch-Documentation#2]
中文版文档呢？放出来的怎么都是英文版文档呢？
龙芯来自中国，我们把中文作为第一支持语言，不过份吧？
不管是从教育，或者吸引国内开发者来说，一份中文文档，有必要的吧？功在当代，利在千秋。

不觉得就算优先提供英文文档，又会有多少外国人愿意真正支持和帮助龙芯发展。

**Comment by ShuiHuo** [comment]
https://github.com/loongson/LoongArch-Documentation/releases

**Comment by chenhuacai** [comment]
> 中文版文档呢？放出来的怎么都是英文版文档呢？
> 龙芯来自中国，我们把中文作为第一支持语言，不过份吧？
> 不管是从教育，或者吸引国内开发者来说，一份中文文档，有必要的吧？功在当代，利在千秋。
> 
> 不觉得就算优先提供英文文档，又会有多少外国人愿意真正支持和帮助龙芯发展。

因为龙芯不仅是中国的，而且是世界的，:)

**Comment by CC2130** [comment]
> > 中文版文档呢？放出来的怎么都是英文版文档呢？
> > 龙芯来自中国，我们把中文作为第一支持语言，不过份吧？
> > 不管是从教育，或者吸引国内开发者来说，一份中文文档，有必要的吧？功在当代，利在千秋。
> > 不觉得就算优先提供英文文档，又会有多少外国人愿意真正支持和帮助龙芯发展。
> 
> 因为龙芯不仅是中国的，而且是世界的，:)

方丈，翻译翻译，什么不仅？￥_￥

**Comment by cnmade** [comment]
![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
没看到中文的源代码。也放出来？

先服务于祖国，再服务于世界可好？

**Comment by LinuxResearcher** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> 没看到中文的源代码。也放出来？
> 
> 先服务于祖国，再服务于世界可好？

想看中文的源代码，要不你先创造一款能流行于全世界的全中文编程语言，然后可以写个脚本，一键转换。
至于先服务于祖国再服务于世界：第一，龙芯哪款产品不是先卖国内服务祖国再出口服务世界，龙芯哪个文档不是先有中文版再翻译英文版；第二，祖国也是世界的一部分，服务于祖国就是在服务世界。
我们要构建人类命运共同体，不能只想着自己，在做好自己的同时也要方便世界其他国家、其他语言的人民，以开放、包容的心态构建一个服务全人类的社区。

**Comment by FreeFlyingSheep** [comment]
> ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> 没看到中文的源代码。也放出来？
> 
> 先服务于祖国，再服务于世界可好？

目前该项目主要用于对外提供 LoongArch 文档的英文翻译，相应的中文原版已经在 Releases 界面提供，并在 README 中注明。
如您所见，中文原版是 **PDF** 格式的，为了方便翻译和展示我们采用了 **AsciiDoc** 格式。
这是一个 **开源项目**，我们欢迎 **任何人** 来提交中文版的 AsciiDoc 或者其他语言的翻译。
显然仅靠我们是不够的，您可以 Fork 该项目，参考原版 PDF，根据项目规范来书写中文的 AsciiDoc 文档，然后提 PR，为龙芯作贡献，为开源社区作贡献，自然也是为祖国作贡献，祖国需要您！

**Comment by cnmade** [comment]
> > ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> > 没看到中文的源代码。也放出来？
> > 先服务于祖国，再服务于世界可好？
> 
> 想看中文的源代码，要不你先创造一款能流行于全世界的全中文编程语言，然后可以写个脚本，一键转换。
> 至于先服务于祖国再服务于世界：第一，龙芯哪款产品不是先卖国内服务祖国再出口服务世界，龙芯哪个文档不是先有中文版再翻译英文版；第二，祖国也是世界的一部分，服务于祖国就是在服务世界。
> 我们要构建人类命运共同体，不能只想着自己，在做好自己的同时也要方便世界其他国家、其他语言的人民，以开放、包容的心态构建一个服务全人类的社区。

说的好呀，如果是先有中文版，那把中文asciidoc 源代码放出来就好了。

至于你其它的喷点我就忽略了。道不同不相与谋，你也不懂我说啥，我也管你怎么想

**Comment by cnmade** [comment]
> > ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> > 没看到中文的源代码。也放出来？
> > 先服务于祖国，再服务于世界可好？
> 
> 目前该项目主要用于对外提供 LoongArch 文档的英文翻译，相应的中文原版已经在 Releases 界面提供，并在 README 中注明。
> 如您所见，中文原版是 **PDF** 格式的，为了方便翻译和展示我们采用了 **AsciiDoc** 格式。
> 这是一个 **开源项目**，我们欢迎 **任何人** 来提交中文版的 AsciiDoc 或者其他语言的翻译。
> 显然仅靠我们是不够的，您可以 Fork 该项目，参考原版 PDF，根据项目规范来书写中文的 AsciiDoc 文档，然后提 PR，为龙芯作贡献，为开源社区作贡献，自然也是为祖国作贡献，祖国需要您！

好的，也就是说目前仅有英文版的asciidoc 是吧，没有中文的。如果有，那肯定放出来了。

如果源代码不是asciidoc, 那会是什么呢？最原始的文档的源文件是latex 还是 docx之类的存放的呢？

**Comment by LinuxResearcher** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> > > 没看到中文的源代码。也放出来？
> > > 先服务于祖国，再服务于世界可好？
> > 
> > 
> > 想看中文的源代码，要不你先创造一款能流行于全世界的全中文编程语言，然后可以写个脚本，一键转换。
> > 至于先服务于祖国再服务于世界：第一，龙芯哪款产品不是先卖国内服务祖国再出口服务世界，龙芯哪个文档不是先有中文版再翻译英文版；第二，祖国也是世界的一部分，服务于祖国就是在服务世界。
> > 我们要构建人类命运共同体，不能只想着自己，在做好自己的同时也要方便世界其他国家、其他语言的人民，以开放、包容的心态构建一个服务全人类的社区。
> 
> 说的好呀，如果是先有中文版，那把中文asciidoc 源代码放出来就好了。
> 
> 至于你其它的喷点我就忽略了。道不同不相与谋，你也不懂我说啥，我也管你怎么想

喷点？你这个喷子知道这个项目是干什么的嘛就来喷，反而我成喷子了。对你这种东西，我只能说物以类聚，你这种东西是听不懂我们人在说什么的，你滚好不送。

**Comment by FreeFlyingSheep** [comment]
> > > ![image](https://user-images.githubusercontent.com/278153/124859044-b909e080-dfe1-11eb-8b43-b7da8be39391.png)
> > > 没看到中文的源代码。也放出来？
> > > 先服务于祖国，再服务于世界可好？
> > 
> > 
> > 目前该项目主要用于对外提供 LoongArch 文档的英文翻译，相应的中文原版已经在 Releases 界面提供，并在 README 中注明。
> > 如您所见，中文原版是 **PDF** 格式的，为了方便翻译和展示我们采用了 **AsciiDoc** 格式。
> > 这是一个 **开源项目**，我们欢迎 **任何人** 来提交中文版的 AsciiDoc 或者其他语言的翻译。
> > 显然仅靠我们是不够的，您可以 Fork 该项目，参考原版 PDF，根据项目规范来书写中文的 AsciiDoc 文档，然后提 PR，为龙芯作贡献，为开源社区作贡献，自然也是为祖国作贡献，祖国需要您！
> 
> 好的，也就是说目前仅有英文版的asciidoc 是吧，没有中文的。如果有，那肯定放出来了。
> 
> 如果源代码不是asciidoc, 那会是什么呢？最原始的文档的源文件是latex 还是 docx之类的存放的呢？

我们能获取到的文档仅限于 PDF 版，如果对原始文档有疑问请联系中文文档中提供的邮箱，我想您一开始的疑问已经得到解答了，为了避免额外的争吵，我决定关闭这个 issue。

**Comment by cnmade** [comment]
以上，感谢各位的解答。本来以为这里是龙芯官方的文档组织，那么现在看并不是官方的。是我多虑了。

另外对于@LinuxResearcher 这样的说法，只能说不齿。开小号上来喷人，提不出一点有意义的问题。哪凉快哪呆着去。

**Comment by chenhuacai** [comment]
> 以上，感谢各位的解答。本来以为这里是龙芯官方的文档组织，那么现在看并不是官方的。是我多虑了。
> 
> 另外对于@LinuxResearcher 这样的说法，只能说不齿。开小号上来喷人，提不出一点有意义的问题。哪凉快哪呆着去。

这里是龙芯官方的开发者创建的，但是不属于官方文档编辑部门。

**Comment by cnmade** [comment]
了解了，我正好奇呢。因为如果是官方的，为什么git仓库中只有英文的asciidoc 源代码，并无中文。也正是由此，不懂就提了一问。
因为还是希望能建立完善的文档，勘误流程，这样，任何人，看到一点点问题，或者发现需要补足的，都可以加入贡献。

来提问，也是因为有一点点想加入贡献的想法。

不然的话，费这么多时间和精力关注这个干什么。我去打王者荣耀不香么。

祝龙芯越来越好。

**Comment by zarraxx** [comment]
08年的时候，我看Intel CPU手册，没办法只能硬啃茫茫多的英文。现在看loongarch的手册，既有中文版，又有英文版，交叉着看还能顺便学习英文，很知足了。
