### ISSUE TITLE
Loongson 3A5000 F{MAX/MIN}.{S/D} does not matches IEEE 754-2008

### ISSUE THREAD

**Issue by xry111** [loongson/LoongArch-Documentation#21]
In the documentation (both Chinese and English) those instructions are said to match the behavior of IEEE 754-2008 `maxNum` and `minNum` operations.

IEEE 754-2008 says if one operand of those operations is a signaling NaN, the execution should signal and produce a quiet NaN.  For example, according to IEEE 754-2008, the result of `maxNum(sNaN, 1.0)` should be `qNaN`.

OTOH, the test on Loongson 3A5000 shows the instructions signals for `sNaN`, but returns another, non-NaN operand instead of a `qNaN`.  For example, `fmax.s $f0, $f0, $f1` puts `1.0f` into `$f0` when `$f0` contains `sNaN` and `$f1` contains `1.0f`.  This does not match IEEE 754-2008, but matches the behavior of LLVM minnum/maxnum intrinsics.

IMO the documentation should be updated to show the difference.  I'm not sure if the descriptions for other floating-point instructions need to be updated as well.

**Comment by chenglulu326** [comment]
Can you give me a test case？

**Comment by chenglulu326** [comment]
> In the documentation (both Chinese and English) those instructions are said to match the behavior of IEEE 754-2008 `maxNum` and `minNum` operations.
> 
> IEEE 754-2008 says if one operand of those operations is a signaling NaN, the execution should signal and produce a quiet NaN. For example, according to IEEE 754-2008, the result of `maxNum(sNaN, 1.0)` should be `qNaN`.
> 
> OTOH, the test on Loongson 3A5000 shows the instructions signals for `sNaN`, but returns another, non-NaN operand instead of a `qNaN`. For example, `fmax.s $f0, $f0, $f1` puts `1.0f` into `$f0` when `$f0` contains `sNaN` and `$f1` contains `1.0f`. This does not match IEEE 754-2008, but matches the behavior of LLVM minnum/maxnum intrinsics.
> 
> IMO the documentation should be updated to show the difference. I'm not sure if the descriptions for other floating-point instructions need to be updated as well.

Can you give me a test case?
