### ISSUE TITLE
Please amend the english version of ABI with a full description for the deatails

### ISSUE THREAD

**Issue by shushanhf** [loongson/LoongArch-Documentation#37]
**Describe the bug:**

**Expected behavior:**

**Additional context:**

Now,the page of https://github.com/loongson/LoongArch-Documentation/blob/main/docs/LoongArch-ELF-ABI-EN.adoc
for the ABI is too brief.
Especially the details for how the structs passed.

**Comment by FreeFlyingSheep** [comment]
cc @ChenghuaXu @scylaac

**Comment by shushanhf** [comment]
This had been repeated with the https://github.com/loongson/LoongArch-Documentation/pull/32 .
So closed this issue.
