### ISSUE TITLE
Wrong translation of LU52I.D pseudocode

### ISSUE THREAD

**Issue by rajdakin** [loongson/LoongArch-Documentation#40]
**Describe the bug:**

File: https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
Section 2.2.1.4
Pseudocode for the `LU52I.D` instruction: it says that `LU52I.D` does not depend on `rj`:
`GR[rd] = {si12, GR[rd][51:0]}`

**Expected behavior:**

The chinese version contains the correct version: `GR[rd] = {si12, GR[rj][51:0]}` (notice the second `rd` that changed into `rj`).

**Additional context:**

All other places that I checked does not contain the issue.

**Comment by FreeFlyingSheep** [comment]
Thanks for pointing this out.
