### ISSUE TITLE
glib2 构建失败

### ISSUE THREAD

**Issue by yetist** [loongson/LoongArch-Documentation#45]
使用最新工具链，构建 glib2 失败。失败的构建命令如下：
```
/usr/sbin/ld -r -b binary gio/tests/test5.gresource -o gio/tests/test_resources.o
/usr/sbin/objcopy --add-symbol _g_binary_test1_resource_data=.data:0 gio/tests/test_resources.o gio/tests/test_resources2.o
cc  -o gio/tests/resources gio/tests/test_resources2.o gio/tests/resources.p/meson-generated_.._test_resources.c.o gio/tests/resources.p/meson-generated_.._test_resources2.c.o gio/tests/resources.p/meson-generated_.._digit_test_resources.c.o gio/tests/resources.p/meson-generated_.._test_resources_binary.c.o gio/tests/resources.p/resources.c.o -flto -Wl,--as-needed -Wl,--no-undefined -pie -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -mabi=lp64d -march=loongarch64 -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fstack-clash-protection -DG_DISABLE_CAST_CHECKS '-Wl,-rpath,$ORIGIN/../../glib:$ORIGIN/../../gmodule:$ORIGIN/../../gobject:$ORIGIN/..:/usr/lib64/../lib64' -Wl,-rpath-link,/archlinux/build/glib2/src/build/glib -Wl,-rpath-link,/archlinux/build/glib2/src/build/gmodule -Wl,-rpath-link,/archlinux/build/glib2/src/build/gobject -Wl,-rpath-link,/archlinux/build/glib2/src/build/gio -Wl,-rpath-link,/usr/lib64/../lib64 -Wl,--start-group glib/libglib-2.0.so.0.7000.4 gmodule/libgmodule-2.0.so.0.7000.4 gobject/libgobject-2.0.so.0.7000.4 gio/libgio-2.0.so.0.7000.4 -Wl,--end-group
/usr/sbin/ld: gio/tests/test_resources2.o: can't link different ABI object.
/usr/sbin/ld: failed to merge target specific data of file gio/tests/test_resources2.o
collect2: 错误：ld 返回 1
```
出错原因：使用 `ld` 和 `objcopy` 生成的 `.o` 文件，其 `e_flags` 标志值为 `0x0`，无法和其他 `e_flags` 值为 `0x3` 的.o 文件一起链接。

```
$ readelf -h gio/tests/test_resources.o gio/tests/test_resources2.o gio/tests/resources.p/meson-generated_.._test_resources.c.o|grep 标志
  标志：             0x0                        
  标志：             0x0                            
  标志：             0x3, LP64, DOUBLE-FLOAT   
```
相关 [规范](https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-CN.html#_e_flags_abi_%E7%B1%BB%E5%9E%8B%E5%92%8C%E7%89%88%E6%9C%AC%E6%A0%87%E8%AE%B0) 中 `0x0` 为保留值，`0x3` 表示 `lp64d`，需手工修改 gio/tests/test_resources.o、gio/tests/test_resources2.o 文件，将 `0x30` 处的 `0x00` 修改为 `0x03` 即可链接成功。

有什么办法可以自动构建成功？

**Comment by xen0n** [comment]
看上去这个使用姿势不产生代码，只是用来把一些数据塞进最终文件？

我们是否可以放宽对 `e_flags` 的检查，只对贡献代码段的那些输入目标文件才检查 `e_flags` 兼容性？

**Comment by xry111** [comment]
这问题在 MIPS 甚至 x86 上已经有了：https://gitlab.gnome.org/GNOME/glib/-/issues/1715

上游跟我说“你要修你交个 MR”，我又懒，然后每次就手动编辑下 `build.ninja` :(

**Comment by xry111** [comment]
RISCV 那边提的是 eflags = 0 表示可以随便链接 (忘了在哪看到的了)。

**Comment by MaskRay** [comment]
> 补丁已经合并到上游了，我这边用最新的 ld 测试编译 glib2 没有问题。

Changing ld is not an elegant solution... e_flags is a pure ELF header check and sections should not be involved to perform the check. I think the right solution is to update input e_flags so that ld doesn't need any magic.

**Comment by xry111** [comment]
> > 补丁已经合并到上游了，我这边用最新的 ld 测试编译 glib2 没有问题。
> 
> Changing ld is not an elegant solution... e_flags is a pure ELF header check and sections should not be involved to perform the check. I think the right solution is to update input e_flags so that ld doesn't need any magic.

You may develop a more elegant solution if you've got some spare time.

To me the most elegant solution is to stop using eflags, and mangle the symbol names of which behavior may be ABI dependent, like:

```
int foo(double x) { ... }
```

should generate a symbol `foo.larch_abi_lp64d`, OTOH

```
int bar(int x) { ... }
```

should generate `foo`, w/o the suffix because it's calling convention is independant on the ABI.

And in this specific case, the symbols `_binary_*_{start, end}` generated by `ld -r -b binary` shouldn't be mangled.

But I doubt if my solution will ever be considered by others...

**Comment by yetist** [comment]
类似情况又发现一个包，mupdf，看来需要把这个补丁拿过来用下了。

**Comment by yetist** [comment]
补丁对 mupdf 也有效， :+1:
