### ISSUE TITLE
支持LDC编译器

### ISSUE THREAD

**Issue by szly-jerry** [loongson/LoongArch-Documentation#52]
请在龙芯平台上支持D语言编译器LDC（基于LLVM的跨平台编译器且支持交叉编译）便于后续多个旧项目代码的编译与适配。

**Comment by xen0n** [comment]
LLVM 已经在上游 review 着了，不用急

**Comment by szly-jerry** [comment]
目前LLVM8.0.48已可用，但是LDC（https://wiki.dlang.org/Building_LDC_from_source）编译遇到问题

**Comment by xen0n** [comment]
建议等新世界（上游），他们正在做，我在帮忙 review，等上游支持了你就当 x86 AArch64 RV 这些平台一样用 LA，就不用折腾了

否则你即便现在基于他们这个老代码跑通了，到时候上游一支持，你还得再改

**Comment by szly-jerry** [comment]
好的，听你意见不吃亏，谢谢！

**Comment by xen0n** [comment]
FYI: LDC 上游一个月前[把 LLVM 最低版本要求提到 9.0 了](https://github.com/ldc-developers/ldc/commit/bdef01e7cc568842a64ffc30cd0304ffe0a12883)，你估计是因为这个被坑了。急的话你用个旧版本，不急就等吧

**Comment by xry111** [comment]
> FYI: LDC 上游一个月前[把 LLVM 最低版本要求提到 9.0 了](https://github.com/ldc-developers/ldc/commit/bdef01e7cc568842a64ffc30cd0304ffe0a12883)，你估计是因为这个被坑了。急的话你用个旧版本，不急就等吧

我有强行 rebase 到 14.x 的 LLVM (https://github.com/xry111/llvm-project/tree/xry111/loongarch-14)，如果你不怕它挂掉可以试一试 (我拿这玩意跑 Rustc 编译 Rustc 本身，以及 Spidermonkey 和 Librsvg 没有问题，但是如果 LLVM 进上游过慢的话我会先考虑用 libgccjit 搞一版看看能不能推 Rustc 上游 —— off topic)
