### ISSUE TITLE
Documentation links from README are broken.

### ISSUE THREAD

**Issue by ZipCPU** [loongson/LoongArch-Documentation#7]
**Describe the bug:**

The links on the main README page don't work.

**Steps to reproduce:**

Open the main github page for the project, scroll to the readme, and click on any link other than the original documentation links.

**Expected behavior:**

Documents should open when clicked upon.

**Screenshots:**

**Additional context:**

It looks like the links are simply missing the /doc directory reference.

**Environment:**

- Operating system:
- Browser/application:
- Browser/application version:

**Comment by FreeFlyingSheep** [comment]
Thanks for pointing this out.
Now the links on the `README.adoc` work.

**Comment by ZipCPU** [comment]
Thank you!
